---
title: "Pseudocode"
---

This document contains a description of the different public functions,
classes, and CLI commands, as well as their signatures, docstrings, and
some pseudocode as a potential implementation. It primarily serves as a
reference for us to develop from and track what has been finished and
what remains to be done.

## Classes

### `Config`

This class contains all the configuration settings for styling the
documentation. It represents a one-to-one mapping to the settings
provided in the `.fl.toml` or `pyproject.toml` file.

```` python
from dataclasses import dataclass
from typing import Literal, Optional

# TODO: Might have to use pydantic instead to run basic checks when creating the class...?
@dataclass(frozen=True)
class Config:
    """Configuration settings for styling the documentation.

    See the [guide](LINK) on how to set up custom styles and sections. See also `Section` for
    more details on how to set up sections.

    Attributes:
        style (Literal["quarto-book", "custom"]): Whether to use a built-in style or to use a custom one.
            Default is the "quarto-book" style. If you want to use a custom style,
            set this to "custom" and provide the path to the templates in `template_dir`.
        template_dir (Optional[Path]): If `style` is "custom", this should be the directory path
            to the [Jinja2](https://jinja.palletsprojects.com/en/stable/) template files. The directory
            **must** contain one template file for each `Section.contents` type used in the `sections`
            attribute.
        sections (Optional[list[Section]]): List of `Section` classes that dictate one or more sections
            to create for the documentation output, including location and content types.

    Examples:
        ``` python
        # A config using the built-in `quarto-book` style
        config = Config(
            style="quarto-book"
        )

        # A custom config with only `package` contents in one section
        config = Config(
            style="custom",
            template_dir=Path("templates"),
            sections=[
                Section(
                    output_path=Path("docs/"),
                    contents=["package"]
                )
            ]
        )

        # A custom config with multiple sections and content types
        config = Config(
            style="custom",
            template_dir=Path("templates"),
            sections=[
                Section(
                    output_path=Path("docs/package.qmd"),
                    contents=["package", "license", "contributors"]
                ),
                # Section that outputs each resources as a file in the `resources/` folder
                Section(
                    output_path=Path("docs/resources/"),
                    contents=["resources"]
                )
            ]
        ```
    """
    style: Literal["quarto-book", "custom"] = "quarto-book"
    template_dir: Optional[Path] = None
    sections: Optional[list[Section]] = None
````

### `Section`

```` python
from dataclasses import dataclass
from typing import Literal, Optional
from pathlib import Path

@dataclass(frozen=True)
class Section:
    """A section of the documentation with specific `datapackage.json` properties.

    See the [guide](LINK) on how to set up custom styles and sections.

    Attributes:
        output_path (Optional[Path]): The output path for this section. If `None`, it will print
            to the screen as a formatted string that follows the `"default-terminal"` style.
            If a directory is provided, files will be created for each content type that have
            a `name` property (e.g. `resources` or `resource-schema-fields`) For example,
            if `output_path` is `Path("docs/")` and `contents` is `["resources"]`, then each resource
            will be output to `docs/{resource_name}.md` (or whichever output format is used in the
            Jinja2 template files). If a file path is provided, all content types will be
            output to that single file.
        contents (list[Literal[...]]): List of content types to include in this
            section. Must be one or more of the types listed. Each content type must have a
            corresponding Jinja2 template file in the `template_dir` of the same name (e.g.
            `package.md.jinja2` or `resources.rst.jinja2`).

    Examples:
        ``` python
        # A section that contains only the package and contributors content types,
        # saved to the `docs/package.qmd` file.
        Section(
            output_path=Path("docs/package.qmd"),
            contents=["package", "contributors"]
       )
       ```
    """
    output_path: Optional[Path] = None
    # Needs to be one or more of the following strings.
    # TODO: Not sure if this is the best/correct way to ensure option is only one of these.
    contents: list[Literal[
        "package", "contributors", "licenses", "sources", "resources", "resource-schema",
        "resource-licenses", "resource-sources", "resource-schema-fields"
    ]]
````
