---
title: "Using the CLI"
description: "How to use Flower on the command-line."
order: 1
---

Flower's CLI has two commands: `view` which displays a Data Package's
metadata in the terminal, and `build` which generates plain text
documentation files from it. The general pattern for the CLI is:

```{.bash filename="Terminal"}
seedcase-flower COMMAND [ARGS] [OPTIONS]
```

To get an overview of the available commands and flags, run the
following command, which is equivalent to using the `--help` flag:

```{.bash filename="Terminal"}
seedcase-flower
```

```{python}
#| echo: false
import seedcase_soil as so

so.format_output_for_docs(["seedcase-flower"])
```

## Viewing Data Package metadata

To view the metadata in an easy-to-read format optimised for the
terminal, use the `view` command:

```{.bash filename="Terminal"}
seedcase-flower view
```

::: {.callout-tip collapse="true" icon="false"}
### Output

This example shows the output of running `seedcase-flower view` in a
directory containing a `datapackage.json` from the example Data Package
`flora`. Note that the output from `view` is optimized for rendering in
a terminal, so some aspects of it might not display as expected here.

```{python}
#| echo: false
so.format_output_for_docs(["seedcase-flower", "view", str(so.Example.flora.path)])
```
:::

### Viewing metadata in a custom location

By default, `view` looks for a `datapackage.json` file in the current
directory, but you can specify a different path if needed:

```{.bash filename="Terminal"}
seedcase-flower view another/directory/datapackage.json
```

You can also point Flower to a remote Data Package by providing the full
URL to the `datapackage.json`. For example:

```{.bash filename="Terminal"}
seedcase-flower view https://raw.githubusercontent.com/seedcase-project/example-seed-beetle/refs/heads/main/datapackage.json
```

::: {.callout-tip collapse="true" icon="false"}
### Output

Note that the output from `view` is optimized for rendering in a
terminal, so some aspects of it might not display as expected here.

```{python}
#| echo: false
so.format_output_for_docs([
    "seedcase-flower",
    "view",
    "https://raw.githubusercontent.com/seedcase-project/example-seed-beetle/refs/heads/main/datapackage.json",
])
```
:::

For Data Packages on GitHub, use the `gh:` prefix as a shortcut instead
of the full URL:

```{.bash filename="Terminal"}
seedcase-flower view gh:seedcase-project/example-seed-beetle
```

::: {.callout-tip collapse="true" icon="false"}
### Output

Note that the output from `view` is optimized for rendering in a
terminal, so some aspects of it might not display as expected here.

```{python}
#| echo: false
so.format_output_for_docs([
    "seedcase-flower",
    "view",
    "gh:seedcase-project/example-seed-beetle",
])
```
:::

### Styling terminal output

Use the `--style` flag to format the terminal output with any of the
[built-in view styles](/docs/reference/ViewStyle.qmd). For example:

```{.bash filename="Terminal"}
seedcase-flower view --style quarto-one-page gh:seedcase-project/example-seed-beetle
```

<!-- TODO: Update this after another one page style is added so it doesn't use the default style. -->

This output will look identical to the output above, since
`quarto-one-page` is the default style for `view`.

::: {.callout-tip collapse="true" icon="false"}
### Output

Note that the output from `view` is optimized for rendering in a
terminal, so some aspects of it might not display as expected here.

```{python}
#| echo: false
so.format_output_for_docs([
    "seedcase-flower",
    "view",
    "--style",
    "quarto-one-page",
    "gh:seedcase-project/example-seed-beetle",
])
```
:::

`view` only works with single-page
[built-in styles](/docs/reference/Style.qmd); multi-page styles are not
supported.

::: callout-important
`view` is only configurable via command line flags. This means that any
options set in Flower's configuration file are ignored, even those with
the same name as the options passed to `view`.
:::

For more details, see the [view](/docs/reference/view.qmd) reference or
run:

```{.bash filename="Terminal"}
seedcase-flower view --help
```

```{python}
#| echo: false
so.format_output_for_docs(["seedcase-flower", "view", "--help"])
```

## Building documentation from Data Package metadata

To convert Data Package metadata into human-friendly plain text files
for building shareable documentation, such as a website or PDF, use the
`build` command:

```{.bash filename="Terminal"}
seedcase-flower build
```

::: {.callout-tip collapse="true" icon="false"}
### Output

This example shows the output files generated when running
`seedcase-flower build` in a directory containing a `datapackage.json`
from the example Data Package `flora`.

```{python}
#| echo: false
!uv run seedcase-flower build {so.Example.flora.path} --output-dir _temp/
so.format_output_for_docs(["ls", "_temp/"])
```
:::

This command generates one new file, `docs/index.qmd`, since `build` by
default uses the `quarto-one-page` style. The `qmd` extension means that
this file is a [Quarto](https://quarto.org/)-flavored Markdown file.
While this is the default format, you can specify your own custom
templates as detailed in the [custom styles](custom-styles.qmd) guide.

### Changing input and output directory

By default, `build` will look for a `datapackage.json` file in the
current directory, but you can use a different source location if you
want, just like with `view`:

```{.bash filename="Terminal"}
seedcase-flower build another/directory/datapackage.json
```

To generate files in a different location, use the `--output-dir` flag
with a folder name. For example:

```{.bash filename="Terminal"}
seedcase-flower build --output-dir my-dir
```

This will generate `my-dir/index.qmd` instead of `docs/index.qmd`.

### Styling the output

Like `view`, `build` accepts a `--style` option to control how metadata
content and files are organised using one of the
[built-in styles](/docs/reference/Style.qmd). For example, to split each
resource into its own file, use the `quarto-resource-listing` style:

```{.bash filename="Terminal"}
seedcase-flower build --style quarto-resource-listing
```

::: {.callout-tip collapse="true" icon="false"}
### Output

This example shows the output files generated when running
`seedcase-flower build --style quarto-resource-listing` in a directory
containing a `datapackage.json` from the example Data Package `flora`.

```{python}
#| echo: false
!uv run seedcase-flower build {so.Example.flora.path} \
    --output-dir _temp/ \
    --style quarto-resource-listing
so.format_output_for_docs(["ls", "_temp/"])
```
:::

Like the default `quarto-one-page` style, `quarto-resource-listing`
creates a `docs/index.qmd`. In addition, it creates a separate file for
each data resource in the `docs/resources/` folder.

You can see examples of the available built-in styles on the
[Examples](/docs/examples/index.qmd) page and read more about how to
create your own custom style in the
[custom styles](/docs/guide/custom-styles.qmd) guide.

<!-- TODO: Add section about using `template-dir` option -->

For more details, see the [build](/docs/reference/build.qmd) reference
or run:

```{.bash filename="Terminal"}
seedcase-flower build --help
```

```{python}
#| echo: false
so.format_output_for_docs(["seedcase-flower", "build", "--help"])
```
